# Generated by Django 5.0.6 on 2024-05-21 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='devices/', verbose_name='Изображение')),
                ('main', models.BooleanField(default=False, verbose_name='Основное изображение')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.device', verbose_name='Устройство')),
            ],
        ),
    ]
