# Generated by Django 5.0.6 on 2024-05-21 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_deviceimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceimage',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.device', verbose_name='Устройство'),
        ),
    ]
